package dev.belalkhan.performanceoverlay

private const val benchmarkRequirements = """

Benchmark requirements: Work through the problem in multiple explicit stages. Include assumptions, derivations, edge cases, numerical examples, at least two substantial tables, pseudocode or Kotlin where relevant, a verification pass that challenges the initial conclusions, and a final synthesis. Do not abbreviate sections or skip intermediate reasoning. Target 2,000 to 2,500 words so generation is sustained long enough to expose throughput and thermal behavior.
"""

internal val samplePrompts = listOf(
    """Design an offline-first health journal architecture for Android. Compare Room-only, operation-log, and CRDT-based synchronization. Model concurrent edits, deletion, clock drift, corrupt local state, interrupted migrations, key loss, compromised servers, and multi-device recovery. Explain schema design, conflict resolution, encryption, privacy boundaries, background work, observability, and testing. Produce Kotlin interfaces and a phased delivery plan, then defend one final architecture.""",
    """Act as a senior algorithms instructor and solve the traveling salesperson problem for 18 cities using Held-Karp dynamic programming with bitmasks. Derive and prove the recurrence, trace a concrete six-city weighted example state by state, calculate time and memory requirements for 18, 22, and 26 cities, and provide robust Kotlin code. Compare it with branch-and-bound, nearest-neighbor, Christofides, and simulated annealing, including counterexamples and implementation pitfalls.""",
    """Create a complete technical design for peer-to-peer Android messaging without internet using Bluetooth LE and Wi-Fi Direct. Specify discovery, authenticated identity, key exchange, encrypted sessions, message ordering, retries, duplicate suppression, group membership, attachment chunking, resumability, battery limits, malicious peers, and process death. Include wire formats, state machines, Kotlin models, protocol pseudocode, threat analysis, and a fault-injection test plan.""",
    """Investigate a hypothetical Android app whose CPU-based local LLM inference becomes progressively slower during a 30-minute session while reported memory remains stable. Build a rigorous root-cause tree covering thermal throttling, DVFS, heterogeneous cores, scheduler migration, memory bandwidth, page faults, garbage collection, JNI overhead, Compose recomposition, and token callbacks. For every hypothesis define evidence, instrumentation, controlled experiments, predicted observations, confounders, and remediation, then rank the causes using a Bayesian-style evidence update.""",
    """Design and implement a bounded asynchronous task scheduler in Kotlin with priorities, cancellation, deadlines, timeouts, exponential retry with jitter, fairness, backpressure, structured concurrency, and deterministic shutdown. State its invariants, reason through races, starvation, cancellation propagation, and clock behavior, and provide production-quality code plus extensive unit tests for adversarial interleavings. Analyze complexity and memory, simulate an overloaded workload, and critique the design with concrete alternatives.""",
    """Develop a graduate-level tutorial connecting information theory, transformer attention, KV caches, quantization, arithmetic intensity, memory bandwidth, heterogeneous mobile CPUs, DVFS, and thermal limits in on-device language-model inference. Derive the central equations, calculate a numerical Gemma-sized decoding example, distinguish prefill and autoregressive decoding, explain why sustained tokens per second changes as a phone heats, and design a statistically defensible Android benchmark with warmups, repeated trials, confidence intervals, and energy-efficiency estimates.""",
).map { it + benchmarkRequirements }
